stages:
  - build
  - test
  - deploy

default:
  image: docker:dind
  before_script:
    - docker login -u ${REGISTRY_USER} -p ${REGISTRY_PASS} ${REGISTRY_URL}

variables:
  IMAGE_PATH: ${REGISTRY_URL}
  VERSION: v1.0.1

vote-build-job:
  stage: build
  image: docker:dind
  script:
    # - cd vote
    - docker build -t ${IMAGE_PATH}/multirepo-vote:$CI_COMMIT_SHORT_SHA .
    - docker push ${IMAGE_PATH}/multirepo-vote:$CI_COMMIT_SHORT_SHA

vote-test-image:
  stage: test
  needs: ["vote-build-job"]
  script:
    - docker pull ${IMAGE_PATH}/multirepo-vote:$CI_COMMIT_SHORT_SHA
    - echo "vote image test"
    - docker tag ${IMAGE_PATH}/multirepo-vote:$CI_COMMIT_SHORT_SHA ${IMAGE_PATH}/multirepo-vote:${VERSION}
    - docker push ${IMAGE_PATH}/multirepo-vote:${VERSION}

deploy-to-pre-product:
  stage: deploy
  # needs: ["result-service-image-scan"]z
  trigger:
    project: ista/multirepo-devops
    branch: main
